name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 15 * * *"   # 매일 00:00 JST = 15:00 UTC
  workflow_dispatch:        # 수동 실행도 가능하게

permissions:
  contents: write           # 저장소에 푸시 권한 줌

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v5

      - uses: yoshi389111/github-profile-3d-contrib@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}

      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          if git commit -m "generated"; then
            git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
